// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GamePipeline.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestStruct struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestStruct) Reset()         { *m = TestStruct{} }
func (m *TestStruct) String() string { return proto.CompactTextString(m) }
func (*TestStruct) ProtoMessage()    {}
func (*TestStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_84a03f5770c82722, []int{0}
}

func (m *TestStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestStruct.Unmarshal(m, b)
}
func (m *TestStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestStruct.Marshal(b, m, deterministic)
}
func (m *TestStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestStruct.Merge(m, src)
}
func (m *TestStruct) XXX_Size() int {
	return xxx_messageInfo_TestStruct.Size(m)
}
func (m *TestStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_TestStruct.DiscardUnknown(m)
}

var xxx_messageInfo_TestStruct proto.InternalMessageInfo

func (m *TestStruct) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

type C2STestMessage struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2STestMessage) Reset()         { *m = C2STestMessage{} }
func (m *C2STestMessage) String() string { return proto.CompactTextString(m) }
func (*C2STestMessage) ProtoMessage()    {}
func (*C2STestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_84a03f5770c82722, []int{1}
}

func (m *C2STestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2STestMessage.Unmarshal(m, b)
}
func (m *C2STestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2STestMessage.Marshal(b, m, deterministic)
}
func (m *C2STestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2STestMessage.Merge(m, src)
}
func (m *C2STestMessage) XXX_Size() int {
	return xxx_messageInfo_C2STestMessage.Size(m)
}
func (m *C2STestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_C2STestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_C2STestMessage proto.InternalMessageInfo

func (m *C2STestMessage) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type S2CTestMessage struct {
	Sz                   string        `protobuf:"bytes,1,opt,name=sz,proto3" json:"sz,omitempty"`
	LongID               int64         `protobuf:"varint,2,opt,name=longID,proto3" json:"longID,omitempty"`
	TestInts             []int32       `protobuf:"varint,3,rep,packed,name=testInts,proto3" json:"testInts,omitempty"`
	TestStructs          []*TestStruct `protobuf:"bytes,4,rep,name=testStructs,proto3" json:"testStructs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *S2CTestMessage) Reset()         { *m = S2CTestMessage{} }
func (m *S2CTestMessage) String() string { return proto.CompactTextString(m) }
func (*S2CTestMessage) ProtoMessage()    {}
func (*S2CTestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_84a03f5770c82722, []int{2}
}

func (m *S2CTestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CTestMessage.Unmarshal(m, b)
}
func (m *S2CTestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CTestMessage.Marshal(b, m, deterministic)
}
func (m *S2CTestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CTestMessage.Merge(m, src)
}
func (m *S2CTestMessage) XXX_Size() int {
	return xxx_messageInfo_S2CTestMessage.Size(m)
}
func (m *S2CTestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CTestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_S2CTestMessage proto.InternalMessageInfo

func (m *S2CTestMessage) GetSz() string {
	if m != nil {
		return m.Sz
	}
	return ""
}

func (m *S2CTestMessage) GetLongID() int64 {
	if m != nil {
		return m.LongID
	}
	return 0
}

func (m *S2CTestMessage) GetTestInts() []int32 {
	if m != nil {
		return m.TestInts
	}
	return nil
}

func (m *S2CTestMessage) GetTestStructs() []*TestStruct {
	if m != nil {
		return m.TestStructs
	}
	return nil
}

type C2SJoin struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SJoin) Reset()         { *m = C2SJoin{} }
func (m *C2SJoin) String() string { return proto.CompactTextString(m) }
func (*C2SJoin) ProtoMessage()    {}
func (*C2SJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_84a03f5770c82722, []int{3}
}

func (m *C2SJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SJoin.Unmarshal(m, b)
}
func (m *C2SJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SJoin.Marshal(b, m, deterministic)
}
func (m *C2SJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SJoin.Merge(m, src)
}
func (m *C2SJoin) XXX_Size() int {
	return xxx_messageInfo_C2SJoin.Size(m)
}
func (m *C2SJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SJoin.DiscardUnknown(m)
}

var xxx_messageInfo_C2SJoin proto.InternalMessageInfo

type S2CMapInit struct {
	MapRow               int32    `protobuf:"varint,1,opt,name=MapRow,proto3" json:"MapRow,omitempty"`
	MapRandSeeds         []int32  `protobuf:"varint,2,rep,packed,name=MapRandSeeds,proto3" json:"MapRandSeeds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CMapInit) Reset()         { *m = S2CMapInit{} }
func (m *S2CMapInit) String() string { return proto.CompactTextString(m) }
func (*S2CMapInit) ProtoMessage()    {}
func (*S2CMapInit) Descriptor() ([]byte, []int) {
	return fileDescriptor_84a03f5770c82722, []int{4}
}

func (m *S2CMapInit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CMapInit.Unmarshal(m, b)
}
func (m *S2CMapInit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CMapInit.Marshal(b, m, deterministic)
}
func (m *S2CMapInit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CMapInit.Merge(m, src)
}
func (m *S2CMapInit) XXX_Size() int {
	return xxx_messageInfo_S2CMapInit.Size(m)
}
func (m *S2CMapInit) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CMapInit.DiscardUnknown(m)
}

var xxx_messageInfo_S2CMapInit proto.InternalMessageInfo

func (m *S2CMapInit) GetMapRow() int32 {
	if m != nil {
		return m.MapRow
	}
	return 0
}

func (m *S2CMapInit) GetMapRandSeeds() []int32 {
	if m != nil {
		return m.MapRandSeeds
	}
	return nil
}

type S2CMapRand struct {
	LineRandSeed         int32    `protobuf:"varint,1,opt,name=LineRandSeed,proto3" json:"LineRandSeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CMapRand) Reset()         { *m = S2CMapRand{} }
func (m *S2CMapRand) String() string { return proto.CompactTextString(m) }
func (*S2CMapRand) ProtoMessage()    {}
func (*S2CMapRand) Descriptor() ([]byte, []int) {
	return fileDescriptor_84a03f5770c82722, []int{5}
}

func (m *S2CMapRand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CMapRand.Unmarshal(m, b)
}
func (m *S2CMapRand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CMapRand.Marshal(b, m, deterministic)
}
func (m *S2CMapRand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CMapRand.Merge(m, src)
}
func (m *S2CMapRand) XXX_Size() int {
	return xxx_messageInfo_S2CMapRand.Size(m)
}
func (m *S2CMapRand) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CMapRand.DiscardUnknown(m)
}

var xxx_messageInfo_S2CMapRand proto.InternalMessageInfo

func (m *S2CMapRand) GetLineRandSeed() int32 {
	if m != nil {
		return m.LineRandSeed
	}
	return 0
}

func init() {
	proto.RegisterType((*TestStruct)(nil), "protocol.TestStruct")
	proto.RegisterType((*C2STestMessage)(nil), "protocol.C2STestMessage")
	proto.RegisterType((*S2CTestMessage)(nil), "protocol.S2CTestMessage")
	proto.RegisterType((*C2SJoin)(nil), "protocol.C2SJoin")
	proto.RegisterType((*S2CMapInit)(nil), "protocol.S2CMapInit")
	proto.RegisterType((*S2CMapRand)(nil), "protocol.S2CMapRand")
}

func init() { proto.RegisterFile("GamePipeline.proto", fileDescriptor_84a03f5770c82722) }

var fileDescriptor_84a03f5770c82722 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x49, 0xeb, 0xe6, 0x76, 0x36, 0x76, 0x11, 0x44, 0xca, 0xae, 0x4a, 0xae, 0x7a, 0x55,
	0x24, 0x82, 0x2f, 0xd0, 0x82, 0x46, 0x2c, 0x48, 0xe2, 0x0b, 0xc4, 0xed, 0x30, 0x02, 0x35, 0x29,
	0x4b, 0x44, 0xd8, 0x33, 0xf8, 0xd0, 0x92, 0x92, 0x4e, 0xe7, 0x55, 0xf2, 0xff, 0xe7, 0x3b, 0x87,
	0x0f, 0xe8, 0xa3, 0xfe, 0xc0, 0x57, 0x33, 0x60, 0x6f, 0x2c, 0xd6, 0xc3, 0xd1, 0x05, 0x47, 0x17,
	0xe3, 0xb3, 0x73, 0x3d, 0xdb, 0x02, 0xbc, 0xa1, 0x0f, 0x2a, 0x1c, 0x3f, 0x77, 0x81, 0xae, 0x81,
	0xe8, 0x82, 0x94, 0xa4, 0x9a, 0x49, 0xa2, 0x59, 0x09, 0x9b, 0x86, 0xab, 0x38, 0xee, 0xd0, 0x7b,
	0x7d, 0x40, 0xba, 0x81, 0x4c, 0xb4, 0x09, 0xc8, 0x44, 0xcb, 0xbe, 0x09, 0x6c, 0x14, 0x6f, 0xfe,
	0x21, 0xfe, 0x34, 0x22, 0x4b, 0x99, 0xf9, 0x13, 0xbd, 0x85, 0x79, 0xef, 0xec, 0x41, 0xb4, 0x45,
	0x56, 0x92, 0x2a, 0x97, 0x29, 0xd1, 0x2d, 0x2c, 0x02, 0xfa, 0x20, 0x6c, 0xf0, 0x45, 0x5e, 0xe6,
	0xd5, 0x4c, 0x9e, 0x33, 0x7d, 0x80, 0x55, 0x38, 0x4b, 0xf9, 0xe2, 0xaa, 0xcc, 0xab, 0x15, 0xbf,
	0xa9, 0x27, 0xe9, 0xfa, 0xd7, 0x58, 0xfe, 0x05, 0xd9, 0x12, 0xae, 0x1b, 0xae, 0x9e, 0x9d, 0xb1,
	0xec, 0x09, 0x40, 0xf1, 0xa6, 0xd3, 0x83, 0xb0, 0x26, 0x44, 0x89, 0x4e, 0x0f, 0xd2, 0x7d, 0x25,
	0xf7, 0x94, 0x28, 0x83, 0x75, 0xfc, 0x69, 0xbb, 0x57, 0x88, 0x7b, 0x5f, 0x64, 0xa3, 0xc8, 0x45,
	0xc7, 0xee, 0xa6, 0x4b, 0xb1, 0x8a, 0x1b, 0x2f, 0xc6, 0xe2, 0x34, 0x4e, 0xf7, 0x2e, 0xba, 0xf7,
	0xf9, 0x28, 0x7a, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xb1, 0xfd, 0x43, 0x7a, 0x01, 0x00,
	0x00,
}
